import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_logs/flutter_logs.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:network_to_file_image/network_to_file_image.dart';
import 'package:receive_intent/receive_intent.dart' as intents;
import 'package:stack_trace/stack_trace.dart';
import 'package:spaces/spaces.dart';
import 'package:uri_to_file/uri_to_file.dart';
import 'package:wakelock/wakelock.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:shiroikumanojisho/creator.dart';
import 'package:shiroikumanojisho/media.dart';
import 'package:shiroikumanojisho/models.dart';
import 'package:shiroikumanojisho/pages.dart';
import 'package:shiroikumanojisho/utils.dart';

/// Application execution starts here.
void main() {
  /// Run and handle an error zone to customise the action performed upon
  /// an error or exception. This allows for error logging for debug purposes
  /// as well as communicating errors to Crashlytics if enabled.
  runZonedGuarded<Future<void>>(() async {
    /// Necessary to initialise Flutter when running native code before
    /// starting the application.
    final binding = WidgetsFlutterBinding.ensureInitialized();

    /// Install the broadcast-intent → Dart bridge so external
    /// tools (Tasker, etc.) can drive playback controls. The
    /// handler is idle until a reader audio toolbar mounts and
    /// registers its callbacks; intents that arrive before then
    /// are silently dropped (no-op), which is the correct
    /// behaviour — we do not want a stray broadcast to cold-start
    /// audio playback from no context.
    PlaybackIntentBridge.initialise();

    /// Initialise local file-based logging.
    await FlutterLogs.initLogs(
      logLevelsEnabled: [
        LogLevel.INFO,
        LogLevel.WARNING,
        LogLevel.ERROR,
        LogLevel.SEVERE
      ],
      timeStampFormat: TimeStampFormat.DATE_FORMAT_1,
      directoryStructure: DirectoryStructure.FOR_DATE,
      logTypesEnabled: ['device', 'network', 'errors'],
      logFileExtension: LogFileExtension.LOG,
    );

    /// Ensure no pop-in for the app icon.
    binding.addPostFrameCallback((_) async {
      final context = binding.rootElement;
      if (context != null) {
        precacheImage(const AssetImage('assets/meta/icon.png'), context);
      }
    });

    /// Ensure the top and bottom bars are shown at launch and wake prevention
    /// is disabled if not reverted from entering a media source.
    Wakelock.disable();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
    /// Used in order to access and initialise an [AppModel] without requiring
    /// a [WidgetRef].
    final container = ProviderContainer();
    final appModel = container.read(appProvider);
    await appModel.initialise();
    await appModel.applyPlayerOrientation();

    /// Some packages propagate their [StackTrace] in an unusual format as
    /// opposed to the format generated by Dart. This function allows the
    /// Flutter framework to handle such formats so they can be displayed
    /// appropriately.
    FlutterError.demangleStackTrace = (stack) {
      if (stack is Trace) {
        return stack.vmTrace;
      }
      if (stack is Chain) {
        return stack.toTrace().vmTrace;
      }
      return stack;
    };

    /// Start the application, specifying the [ProviderContainer] with the
    /// already initialised [AppModel].
    runApp(
      UncontrolledProviderScope(
        container: container,
        child: const JidoujishoApp(),
      ),
    );
  }, (exception, stack) {
    /// Print error details to the console.
    final details = FlutterErrorDetails(exception: exception, stack: stack);

    /// Log the error.
    FlutterLogs.logError(
      'jidoujisho',
      details.exceptionAsString(),
      stack.toString(),
    );
  });
}

/// Encapsulates theming, spacing and other configurable options pertaining to
/// the entire app, with some parameters dependent on the [AppModel].
class JidoujishoApp extends ConsumerStatefulWidget {
  /// Initialises an instance of the app.
  const JidoujishoApp({super.key});

  @override
  ConsumerState<JidoujishoApp> createState() => _JidoujishoAppState();
}

class _JidoujishoAppState extends ConsumerState<JidoujishoApp>
    with WidgetsBindingObserver {
  final navigatorKey = GlobalKey<NavigatorState>();
  bool _isMainIntent = false;

  late final StreamSubscription _intentsSubscription;

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      /// Receive all intents and parse them depending on which they are.
      intents.ReceiveIntent.getInitialIntent().then(
        (intent) => handleIntent(
          intent: intent,
          isInitial: true,
        ),
      );
      // Attach a listener to the stream for receiving intents.
      _intentsSubscription = intents.ReceiveIntent.receivedIntentStream.listen(
        (intent) => handleIntent(
          intent: intent,
          isInitial: false,
        ),
      );
    });
  }

  @override
  void dispose() {
    _intentsSubscription.cancel();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  void handleIntent({
    required intents.Intent? intent,
    required bool isInitial,
  }) async {
    if (intent == null) {
      return;
    }

    debugPrint(jsonEncode(intent.toMap()));

    switch (intent.action) {
      case 'android.intent.action.MAIN':
        setState(() {
          _isMainIntent = true;
        });
        return;
      case 'android.intent.action.SEND_MULTIPLE':
        List<String> contentUris =
            List<String>.from(intent.extra!['android.intent.extra.STREAM']);
        List<String> paths = [];
        for (int i = 0; i < contentUris.length; i++) {
          paths.add((await toFile(contentUris[i])).path);
        }

        imageShareIntentAction(paths);
        break;
      case 'android.intent.action.SEND':
        String? data = intent.extra!['android.intent.extra.TEXT'];
        if (data != null) {
          textShareIntentAction(data);
        } else {
          String contentUri = intent.extra!['android.intent.extra.STREAM'];
          String path = (await toFile(contentUri)).path;

          imageShareIntentAction([path]);
        }

        break;
      case 'android.intent.action.PROCESS_TEXT':
        String data = intent.extra!['android.intent.extra.PROCESS_TEXT'];
        textContextMenuAction(data);
        return;
      case 'android.intent.action.VIEW':
        String? subtitleUrl = intent.extra?['subtitles_location'];

        if (subtitleUrl == null) {
          if (intent.extra?['subs.enable'] != null) {
            try {
              List<String> subtitles =
                  List<String>.from(intent.extra?['subs.enable']);
              if (subtitles.isNotEmpty) {
                subtitleUrl = subtitles.first;
              }
            } finally {}
          }
        }
        String? title = intent.extra?['title'];
        int? position = intent.extra?['position'];
        if (position != null) {
          position = position ~/ 1000;
        }

        launchNetworkMediaAction(
          videoUrl: intent.data ?? '',
          extra: jsonEncode(intent.extra ?? {}),
          position: position,
          title: title,
        );
        return;
      case 'android.intent.action.WEB_SEARCH':
        String data = intent.extra!['query'];
        textContextMenuAction(data);
        return;
    }
  }

  void textContextMenuAction(String data) {
    if (data.trim().isNotEmpty) {
      appModel.openRecursiveDictionarySearch(
        searchTerm: data,
        killOnPop: true,
      );
    }
  }

  void textShareIntentAction(String data) {
    if (data.startsWith('https://') || data.startsWith('http://')) {
      String? videoId = VideoId.parseVideoId(data);
      if (videoId != null) {
        try {
          launchYoutubeMediaAction(data);
          return;
        } catch (e) {
          debugPrint('Not a YouTube video');
        }
      }

      if (data.toLowerCase().endsWith('.jpg') ||
          data.toLowerCase().endsWith('.jpeg') ||
          data.toLowerCase().endsWith('.png')) {
        appModel.openCreator(killOnPop: true, ref: ref);
        List<NetworkToFileImage> images = [NetworkToFileImage(url: data)];

        Future.delayed(const Duration(milliseconds: 100), () {
          ImageField.instance.setImages(
            appModel: appModel,
            creatorModel: creatorModel,
            cause: EnhancementTriggerCause.manual,
            newAutoCannotOverride: true,
            generateImages: () async {
              return images;
            },
          );
        });
      }
    } else {
      if (data.trim().isNotEmpty) {
        appModel.openCreator(
          creatorFieldValues: CreatorFieldValues(
            textValues: {
              SentenceField.instance: data,
            },
          ),
          killOnPop: true,
          ref: ref,
        );
      }
    }
  }

  void imageShareIntentAction(List<String> paths) {
    if (paths.isEmpty) {
      return;
    }

    appModel.openCreator(killOnPop: true, ref: ref);

    List<NetworkToFileImage> images = paths.map(
      (path) {
        return NetworkToFileImage(
          file: File(path),
        );
      },
    ).toList();

    Future.delayed(const Duration(milliseconds: 100), () {
      ImageField.instance.setImages(
        appModel: appModel,
        creatorModel: creatorModel,
        cause: EnhancementTriggerCause.manual,
        newAutoCannotOverride: true,
        generateImages: () async {
          return images;
        },
      );
    });
  }

  void launchYoutubeMediaAction(String url) async {
    MediaItem item =
        await PlayerYoutubeSource.instance.getMediaItemFromUrl(url);

    Navigator.popUntil(
        appModel.navigatorKey.currentContext!, (route) => route.isFirst);
    if (mounted) {
      await appModel.openMedia(
        ref: ref,
        mediaSource: PlayerYoutubeSource.instance,
        killOnPop: true,
        item: item,
      );
    }
  }

  void launchNetworkMediaAction({
    required String videoUrl,
    required String extra,
    int? position,
    String? title,
  }) async {
    MediaItem item = PlayerNetworkStreamSource.instance.getMediaItemFromUrl(
      videoUrl: videoUrl,
      extra: extra,
      position: position,
      title: title,
    );

    Navigator.popUntil(
        appModel.navigatorKey.currentContext!, (route) => route.isFirst);
    await appModel.openMedia(
      ref: ref,
      mediaSource: PlayerNetworkStreamSource.instance,
      killOnPop: true,
      item: item,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: appModel.navigatorKey,
      home: home,
      locale: locale,
      localizationsDelegates: const [
        JidoujishoLocalizationsDelegate(),
      ],
      supportedLocales: appModel.locales.values,
      themeMode: themeMode,
      theme: appModel.theme,
      darkTheme: appModel.darkTheme,
      // This is responsible for the initialising the global spacing across
      // the entire project, making use of the [spaces] package.
      builder: (context, child) => Spacing(
        dataBuilder: (context) {
          return SpacingData.generate(10);
        },
        // Stack the app's navigator output with a top-right
        // `Indexing:` overlay that paints above everything in the
        // Navigator — including in-page Stacks (half-screen dict
        // popup) and modal dialogs. Driven by the search worker's
        // `[WORKER-INDEX-PROGRESS]` messages via
        // `AppModel.indexBuildNotifier`.
        child: Stack(
          children: [
            child!,
            _IndexBuildOverlay(appModel: appModel),
          ],
        ),
      ),
    );
  }

  /// Responsible for managing global app-wide state.
  AppModel get appModel => ref.watch(appProvider);

  /// Responsible for managing card creator state.
  CreatorModel get creatorModel => ref.watch(creatorProvider);

  /// The application will open to this page upon startup.
  Widget get home => _isMainIntent ? const HomePage() : const Scaffold();

  /// The current theme mode, which by default is based on system setting
  /// and toggleable.
  ThemeMode get themeMode =>
      appModel.isDarkMode ? ThemeMode.dark : ThemeMode.light;

  /// The current locale, dependent on the active target language.
  Locale get locale => appModel.targetLanguage.locale;
}

/// Used to override certain strings.
class JidoujishoLocalizations extends DefaultMaterialLocalizations {
  @override
  String get licensesPageTitle => t.options_attribution;
}

/// Delegate for [JidoujishoLocalizations].
class JidoujishoLocalizationsDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  /// Initialise this delegate.
  const JidoujishoLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) {
    return true;
  }

  @override
  Future<JidoujishoLocalizations> load(Locale locale) {
    return SynchronousFuture<JidoujishoLocalizations>(
        JidoujishoLocalizations());
  }

  @override
  bool shouldReload(JidoujishoLocalizationsDelegate old) => false;
}

/// Top-right indexing-progress overlay. Lives in the
/// `MaterialApp.builder` Stack so it paints above every route,
/// dialog, and in-page Stack — in particular above the reader's
/// half-screen dictionary popup which is rendered in the reader
/// page's own Stack and would otherwise occlude an in-page overlay.
///
/// Renders nothing when no builds are in flight. Otherwise renders
/// "Indexing:" as a header followed by one two-line block per
/// language currently being built — language display name on top,
/// `processed / total` underneath (or "Finalizing…" when processed
/// has caught up to total). This honestly reflects that multiple
/// builds run concurrently in the worker; smaller languages can
/// finish ahead of larger ones, and each one's row disappears when
/// its own build completes.
class _IndexBuildOverlay extends StatelessWidget {
  const _IndexBuildOverlay({required this.appModel});

  final AppModel appModel;

  @override
  Widget build(BuildContext context) {
    return Positioned(
      top: MediaQuery.of(context).padding.top + 8,
      right: 8,
      child: IgnorePointer(
        // The overlay is purely informational — don't let it block
        // taps on the UI beneath it.
        child: ValueListenableBuilder<List<IndexBuildProgress>>(
          valueListenable: appModel.indexBuildNotifier,
          builder: (context, queue, _) {
            if (queue.isEmpty) return const SizedBox.shrink();
            return Material(
              // Material is needed here because we're above MaterialApp's
              // Navigator but outside any page's Scaffold; Text renders
              // with a red "missing material" underline otherwise.
              color: Colors.transparent,
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.7),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text(
                      'Indexing (${queue.length} '
                      '${queue.length == 1 ? 'language' : 'languages'}):',
                      style: const TextStyle(
                        color: Color(0xFFFFFF00),
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    for (final p in queue) ...[
                      const SizedBox(height: 4),
                      Text(
                        appModel.languageDisplayName(p.languageCode),
                        style: const TextStyle(
                          color: Color(0xFFFFFF00),
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Text(
                        (p.total > 0 && p.processed >= p.total)
                            ? 'Finalizing\u2026'
                            : '${_formatThousands(p.processed)} / '
                                '${_formatThousands(p.total)}',
                        style: const TextStyle(
                          color: Color(0xFFFFFF00),
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }

  /// Group a non-negative integer with spaces every 3 digits —
  /// "3 144 545" rather than "3144545". Keeps the progress readout
  /// scannable at a glance. Allocates a StringBuffer per call but
  /// the overlay only repaints a few times per second.
  static String _formatThousands(int n) {
    if (n < 0) return n.toString();
    final s = n.toString();
    if (s.length <= 3) return s;
    final buf = StringBuffer();
    for (int i = 0; i < s.length; i++) {
      if (i > 0 && (s.length - i) % 3 == 0) buf.write(' ');
      buf.write(s[i]);
    }
    return buf.toString();
  }
}
